include:
  - board: nice_nano_v2
    shield: scylla_left
    #artifact-name: left_firmware
    #cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n # Comment for using bluetooth and not the dongle.
    # snippet: studio-rpc-usb-uart # Uncomment to use.
    # cmake-args: -DCONFIG_ZMK_STUDIO=y # Zmk studio with bluetooth.
        
  - board: nice_nano_v2
    shield: scylla_right
    #artifact-name: right_firmware
    #cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n # Comment for using bluetooth and not the dongle.

  # - board: seeeduino_xiao_ble
  #   shield: scylla_dongle
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   artifact-name: dongle_firmware

  # - board: nice_nano_v2
  #   shield: settings_reset
  #   artifact-name: keyboard_reset

  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
  #   artifact-name: dongle_reset
